CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(40) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(24) NOT NULL,
    cpf CHAR(11) NOT NULL UNIQUE,
    phone CHAR(11) NOT NULL,
    token CHAR(8) NOT NULL UNIQUE
);
